FROM {{ docker_image }}

# Define default command.
CMD ["bash"]

COPY app/ app/
WORKDIR /app

# install dependencies
RUN pip install -r requirements.txt

# command to run on container start
CMD [ "python", "./server.py" ]