---
- name: "Creating required directory structure for {{ role_name }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    recurse: yes
    owner: root
  with_items:
    - "{{ required_directory_structure }}"
  become: yes
  register: directory_creation_status

- name: "Generating template files"
  template:
    src: ../templates/{{ item.src }}
    dest: "{{ dir_prod_data_role }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ template_files }}"
  become: yes

- name: "Copying config files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ dir_prod_data_role }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ config_files }}"
  become: yes

# - name: "Build docker image for {{ role_name }}"
#   docker_image:
#     name: "{{docker_registry_url}}/{{ role_name }}"
#     build:
#       path: "{{ dir_prod_data_role }}"
#       pull: yes
#       nocache: yes
#     source: build
#     tag: "{{ branch_name }}"
#     force_source: yes
#     force_tag: yes
#     force_absent: yes
#     state: present
#     push: yes
#   become: yes

- name: "Log to private docker registry and force re-authorization"
  docker_login:
    registry_url: "{{docker_registry_url}}"
    username: "{{docker_registry_username}}"
    password: "{{docker_registry_password}}"
    reauthorize: yes

- name: "Push docker image for {{ role_name }}"
  docker_image:
    name: "{{docker_registry_url}}/{{ role_name }}:{{ branch_name }}"
    repository: "{{docker_registry_url}}/{{ role_name }}:{{ branch_name }}"
    state: present